theme: jekyll-theme-minimal
title: Ayesha Karim
description: Frontend Engineer with expertise in building scalable,high-performance and responsive web applications in React, Typescript and Javascript
